// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPark.Infraestrutura.Persistencia;

#nullable disable

namespace SmartPark.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(SmartParkDbContext))]
    [Migration("20261009224650_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Acesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoNegacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acessos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Acessos_Direcao", "Direcao IN ('Entrada', 'Saida')");

                            t.HasCheckConstraint("CK_Acessos_Metodo", "Metodo IN ('Lpr', 'Rfid', 'QrCode', 'Manual')");

                            t.HasCheckConstraint("CK_Acessos_Status", "Status IN ('Pendente', 'Liberado', 'Negado')");

                            t.HasCheckConstraint("CK_Acessos_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BeneficioAplicado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Paciente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("Atendimentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Atendimentos_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoBeneficio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValorBeneficio")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique();

                    b.ToTable("Convenios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Convenios_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");

                            t.HasCheckConstraint("CK_Convenios_TipoBeneficio", "TipoBeneficio IN ('Isencao', 'Percentual', 'HorasGratis')");

                            t.HasCheckConstraint("CK_Convenios_ValorBeneficio", "ValorBeneficio >= 0");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comprovante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Parcelas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorCobrado")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorTarifa")
                        .HasColumnType("REAL");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId")
                        .IsUnique()
                        .HasFilter("AtendimentoId IS NOT NULL");

                    b.HasIndex("ReservaId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Pagamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagamentos_DuracaoHoras", "DuracaoHoras > 0");

                            t.HasCheckConstraint("CK_Pagamentos_Forma", "Forma IN ('Pix', 'Credito', 'Debito')");

                            t.HasCheckConstraint("CK_Pagamentos_Status", "Status IN ('Pendente', 'Aprovado', 'Estornado')");

                            t.HasCheckConstraint("CK_Pagamentos_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");

                            t.HasCheckConstraint("CK_Pagamentos_Valor", "Valor >= 0");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracaoHoras")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VagaId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorEstimado")
                        .HasColumnType("REAL");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VagaId")
                        .IsUnique()
                        .HasFilter("Status = 'Confirmada'");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Reservas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservas_DuracaoHoras", "DuracaoHoras > 0");

                            t.HasCheckConstraint("CK_Reservas_Status", "Status IN ('Pendente', 'Confirmada', 'Cancelada', 'Concluida')");

                            t.HasCheckConstraint("CK_Reservas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEstrategia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorMaximoDiario")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasFilter("Ativa = 1");

                    b.ToTable("Tarifas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tarifas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");

                            t.HasCheckConstraint("CK_Tarifas_TipoEstrategia", "TipoEstrategia IN ('PorHora', 'Diaria', 'Isenta')");

                            t.HasCheckConstraint("CK_Tarifas_Valor", "Valor >= 0");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Documento")
                        .IsUnique();

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Perfil", "Perfil IN ('Motorista', 'Morador', 'Funcionario', 'Visitante', 'Operador', 'Administrador', 'Manobrista')");

                            t.HasCheckConstraint("CK_Usuarios_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");

                            t.HasCheckConstraint("CK_Usuarios_Tipo", "Tipo IN ('Motorista', 'Morador', 'Visitante', 'Funcionario', 'Paciente', 'Acompanhante')");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("Vagas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator<string>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagRfid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Placa")
                        .IsUnique();

                    b.ToTable("Veiculos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Veiculos_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vagas.VagaComum", b =>
                {
                    b.HasBaseType("SmartPark.Dominio.Entidades.Vaga");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator().HasValue("Comum");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vagas.VagaEletrica", b =>
                {
                    b.HasBaseType("SmartPark.Dominio.Entidades.Vaga");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator().HasValue("Eletrica");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vagas.VagaNominal", b =>
                {
                    b.HasBaseType("SmartPark.Dominio.Entidades.Vaga");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator().HasValue("Nominal");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vagas.VagaPCD", b =>
                {
                    b.HasBaseType("SmartPark.Dominio.Entidades.Vaga");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator().HasValue("PCD");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vagas.VagaPrioritaria", b =>
                {
                    b.HasBaseType("SmartPark.Dominio.Entidades.Vaga");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator().HasValue("Prioritaria");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Vagas.VagaRestrita", b =>
                {
                    b.HasBaseType("SmartPark.Dominio.Entidades.Vaga");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Vagas_Status", "Status IN ('Livre', 'Ocupada', 'Bloqueada', 'Reservada')");

                            t.HasCheckConstraint("CK_Vagas_TenantId", "TenantId IN ('shopping', 'condominium', 'hospital', 'company')");
                        });

                    b.HasDiscriminator().HasValue("Restrita");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Atendimento", b =>
                {
                    b.HasOne("SmartPark.Dominio.Entidades.Convenio", "Convenio")
                        .WithMany()
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Pagamento", b =>
                {
                    b.HasOne("SmartPark.Dominio.Entidades.Atendimento", null)
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartPark.Dominio.Entidades.Reserva", null)
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartPark.Dominio.Entidades.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartPark.Dominio.Entidades.Reserva", b =>
                {
                    b.HasOne("SmartPark.Dominio.Entidades.Vaga", null)
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPark.Dominio.Entidades.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
